# -*- coding: utf-8 -*-
"""Summary app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uEaPUJKZTtOS1la6xJ62uYFUElkGT-GL
"""

!pip install transformers

from transformers import pipeline
from bs4 import BeautifulSoup
import requests

summarizer = pipeline('summarization')

URL = "https://www.blogtrovert.com/how-to-sell-canva-templates/"

r = requests.get(URL)

r.text

soup = BeautifulSoup(r.text,'html.parser')
results = soup.find_all(['h1', 'p'])

text = [result.text for result in results]
article = ' '.join(text)

article = article.replace('.', '.<eos>')
article = article.replace('!', '!<eos>')
article = article.replace('?', '?<eos>')
sentences = article.split('<eos>')

max_chunk =500
current_chunk =0
chunks =[]

for sentence in sentences:
  if len(chunks)== current_chunk +1:
    if len(chunks[current_chunk]) + len(sentence.split(' '))<= max_chunk:
        chunks[current_chunk].extend(sentence.split(' '))
    else:
           current_chunk +=1
           chunks.append(sentence.split(' '))
  else:
           print(current_chunk)
           chunks.append(sentence.split(' '))

for chunk_id in range(len(chunks)):
  chunks[chunk_id] = ' '.join(chunks[chunk_id])

res = summarizer(chunks, max_length=110, min_length=30, do_sample=False)

res

' '.join([summ['summary_text'] for summ in res])

text =' '.join([summ['summary_text'] for summ in res])

with open('summary.txt', 'w') as f:
   f.write("text")

export f: as